FROM nvcr.io/nvidia/tritonserver:22.08-py3

ARG PROJECT_PATH=/project

WORKDIR ${PROJECT_PATH}
SHELL ["/bin/bash", "-c"]

COPY requirements ${PROJECT_PATH}/requirements/

RUN pip install --upgrade pip && \
    pip install torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cpu && \
    pip install -r ${PROJECT_PATH}/requirements/sd.txt
