
name: "pytorch"
backend: "python"
max_batch_size: 32


input [
 {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ 256 ]
  } ,
{
    name: "attention_mask"
    data_type: TYPE_INT32
    dims: [ 256 ]
  }
]
output {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 28 ]
  }

instance_group [
 {
    count: 1
    kind: KIND_CPU
 }
]
