
name: "pipeline"
backend: "python"
max_batch_size: 0

input [
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
input [
  {
    name: "height"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
input [
  {
    name: "width"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
input [
  {
    name: "inference_steps"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]

parameters {
    key: "unet_inchannels"
    value: { string_value: "4" }
}

parameters {
    key: "vae_scale_factor"
    value: { string_value: "8" }
}
